# You can also use any non-zero value if you'd like to have a border
for_window [class=".*"] border pixel 1

#hide_edge_borders horizontal

#gaps inner 10
#gaps outer 0

# Set colors from Xresources
# Change 'color7' and 'color2' to whatever colors you want i3 to use 
# from the generated scheme.
# NOTE: The '#f0f0f0' in the lines below is the color i3 will use if
# it fails to get colors from Xresources.
set_from_resource $fg i3wm.color7 #f0f0f0
set_from_resource $bg i3wm.color0 #f0f0f0
set_from_resource $x1 i3wm.color1 #f0f0f0
set_from_resource $x2 i3wm.color2 #f0f0f0
set_from_resource $x3 i3wm.color3 #f0f0f0
set_from_resource $x4 i3wm.color4 #f0f0f0
set_from_resource $x5 i3wm.color5 #f0f0f0
set_from_resource $x6 i3wm.color6 #f0f0f0
set_from_resource $x8 i3wm.color8 #f0f0f0

## class                 border  backgr. text indicator child_border
#client.focused          $bg     $bg     $fg  $bg       $bg
#client.focused_inactive $bg     $bg     $fg  $bg       $bg
#client.unfocused        $bg     $bg     $fg  $bg       $bg
#client.urgent           $bg     $bg     $fg  $bg       $bg
#client.placeholder      $bg     $bg     $fg  $bg       $bg

#client.background       $bg


# class                 border  backgr. text    indicator child_border
client.focused          $x6 	$x6		$bg		$x1		  $x6
client.focused_inactive $x8 	$x8 	$bg 	$x1   	  $x8
client.unfocused        $x6		$bg 	$fg	 	$x1   	  $x8
client.urgent           #2f343a #900000 #ffffff $x1   	  #900000
client.placeholder      #000000 #0c0c0c #ffffff $x1   	  #0c0c0c

client.background       #ffffff

#### class                 border  backgr. text    indicator child_border
###client.focused          #4c7899 #285577 #ffffff #2e9ef4   #285577
###client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
###client.unfocused        #333333 #222222 #888888 #292d2e   #222222
###client.urgent           #2f343a #900000 #ffffff #900000   #900000
###client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c
###
###client.background       #ffffff

# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:inconsolata 10

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec  --no-startup-id i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
#bindsym $mod+d exec dmenu_run -nb "$bg" -nf "$fg" -sb "$x6" -sf "$bg"
#bindsym $mod+d exec rofi -show combi -combi-modi "run#drun" -modi combi -show-icons
bindsym $mod+d exec rofi -show combi -combi-modi "run#drun" -modi combi -show-icons -no-config
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)

#bar {
#        status_command i3status
#}

exec_always --no-startup-id ~/.i3/polybar.sh &

#exec --no-startup-id polybar wyjek &
#exec --no-startup-id feh --bg-fill ~/tapty/049_dClut0R.jpg
exec --no-startup-id ~/tap.sh &
#exec --no-startup-id watch -n 600 feh --randomize --bg-fill ~/tapty/* &>/dev/null &
#exec_always --no-startup-id compton -b --unredir-if-possible --vsync --glx-no-stencil --config ~/.config/compton/compton.conf
exec --no-startup-id wal --theme sexy-gotham
exec --no-startup-id setxkbmap pl

bindsym Print exec --no-startup-id maim --hidecursor | xclip -selection clipboard -t image/png
bindsym $mod+z exec firefox
bindsym $mod+x exec nautilus
bindsym $mod+c exec /bin/sh "/home/wyjek/jd2/JDownloader2"
bindsym $mod+b exec geany
bindsym $mod+m exec feh --randomize --bg-fill ~/tapty/*
bindsym $mod+n exec ~/vscodium/bin/vscodium
bindsym $mod+Prior exec pamixer -i 2
bindsym $mod+Next exec pamixer -d 2
